---
title: "IVF EDA"
author: "Junbum Kim"
date: "7/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(ggplot2)
library(ggsci)
library(dplyr)
library(ggpubr)
df = read_excel('Metadata.xlsx')
df$PGD_RESULT = factor(df$PGD_RESULT, levels = c("EUP", "ANU", "CxA", "MUT"))
df = df %>% filter(BX_DAY == 6)
colnames(df)[25] = "timepoint"

```


```{r AGE vs EUPLOIDITY STATUS}
my_comparisons <- list( c("EUP", "ANU"), c("ANU", "CxA"), c("CxA", "MUT"), c("EUP", "MUT") ) # , c("EUP", "CxA"), c("ANU", "MUT")

counts = df %>% group_by(PGD_RESULT) %>% tally()

# boxplot
ggboxplot(df, x = "PGD_RESULT", y = "EGG_AGE", color = "PGD_RESULT", palette = 'jco') + 
  stat_compare_means(comparisons = my_comparisons, label = 'p.signif') +
  scale_x_discrete(labels = paste(counts$PGD_RESULT, " (N = ",counts$n,")", sep = "")) +
  xlab('')

```


```{r AGE vs EUPLOIDITY STATUS, fig.height=8, fig.width=11}
p1 = ggplot(df, aes(EGG_AGE, fill = PGD_RESULT, color = PGD_RESULT)) +
  geom_density(aes(y=..count..),alpha = 0.2) + 
  scale_fill_jco() +
  scale_color_jco() +
  theme_pubr() +
  facet_grid(PGD_RESULT ~ ., switch="both") +
  geom_vline(xintercept = 38.38, linetype="dashed", color = "#3CB043", size = 1) + 
  geom_vline(xintercept = 38.77, linetype="dashed", color = "red", size = 1) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

p2 = ggplot(df, aes(EGG_AGE, fill = PGD_RESULT, color = PGD_RESULT)) +
  geom_density(aes(y=..count..),alpha = 0.2) + 
  scale_fill_jco() +
  scale_color_jco() +
  theme_pubr() +
  geom_vline(xintercept = 38.38, linetype="dashed", color = "#3CB043", size = 1) + 
  geom_vline(xintercept = 38.77, linetype="dashed", color = "red", size = 1) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

p1
p2
ggarrange(p1, p2, nrow=2, ncol = 1, common.legend = T)
```



```{r fig.height=8.5, fig.width=11}


dfn = read.csv('meta_numeric.csv')
numbers = dfn[,c(28,29,31,32)]
non_zero = rowSums(is.na(numbers)) == 0
mat = dfn[non_zero, c(28,29,31,32)] %>% as.matrix
mat.pca.model = prcomp(mat)


mat.df = mat %>% as.data.frame
t1 = cor.test(x = mat.df$BMS, y = mat.df$BS)
t2 = cor.test(x = mat.df$BMS, y = mat.df$ICM)
t3 = cor.test(x = mat.df$BMS, y = mat.df$TE)
t4 = cor.test(x = mat.df$ICM, y = mat.df$BS)



p1 = ggplot(mat.df, aes(x = BMS, y = BS)) +
  geom_density_2d_filled() +
  geom_smooth(method = "lm", color = "red", fill="#69b3a2", se = TRUE) +
  theme_pubr() +
  theme(legend.position='none') +
  ggtitle(paste("Pearson Correlation:", round(t1$estimate,2)))
p2 = ggplot(mat.df, aes(x = BMS, y = ICM)) +
  geom_density_2d_filled() +
  geom_smooth(method = "lm", color = "red", fill="#69b3a2", se = TRUE) +
  theme_pubr() +
  theme(legend.position='none') +
  ggtitle(paste("Pearson Correlation:", round(t2$estimate,2)))
p3 = ggplot(mat.df, aes(x = BMS, y = TE)) +
  geom_density_2d_filled() +
  geom_smooth(method = "lm", color = "red", fill="#69b3a2", se = TRUE) +
  theme_pubr() +
  theme(legend.position='none') +
  ggtitle(paste("Pearson Correlation:", round(t3$estimate,2)))
p4 = ggplot(mat.df, aes(x = ICM, y = TE)) +
  geom_density_2d_filled() +
  geom_smooth(method = "lm", color = "red", fill="#69b3a2", se = TRUE) +
  theme_pubr() +
  theme(legend.position='none') +
  ggtitle(paste("Pearson Correlation:", round(t4$estimate,2)))

ggarrange(p1, p2, p3, p4)

dfn.pca = mat.pca.model$x %>% as.data.frame()
dfn.pca$GROUP = dfn$PGD_RESULT[non_zero]
dfn.pca$AGE = dfn$EGG_AGE[non_zero]

dfn.pca.heatmap = dfn.pca %>%
  group_by(GROUP) %>%
  count(GROUP, PC1, PC2) %>%
  as.data.frame

ggplot(dfn.pca, aes(x = AGE, y = PC1)) +
  geom_density_2d_filled() +
  theme_pubr() +
  ylab('Scores PC1 (Var Ex: 89.85%)') + 
  #ylab('PC2 (Var Ex: 3.80%)') +
  facet_wrap(~GROUP) +
  theme(legend.position='none')

```

